name: PMO PR-Jira Report V2 TEST
 
on:
  schedule:
    - cron: "00 15 * * *"
  workflow_dispatch:
    inputs:
      pr_base_branch: 
        description: "Branch for which report to be generated (optional for manual runs,uses repo default branch)"
        required: false
        type: string 
      from_date:
        description: "Start date (UTC, YYYY-MM-DD), Default is start of year"
        required: false
        type: string
      to_date:
        description: "End date (UTC, YYYY-MM-DD),  Default is today"
        required: false
        type: string

permissions:
  pull-requests: read
  issues: read

jobs:
  build-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
       
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr-jira-report
          path: reports/pr-jira-report.xlsx
          if-no-files-found: error

